# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 2ms/step - loss: 26.4708
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 27.0471
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 26.6980
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 26.8570
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 26.7023
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 26.7069
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 26.4567
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 26.9536
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 26.5011
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 26.4624
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 26.5565
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss: 26.7052
E

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

60/60 [==============================] - 0s 1ms/step
[[431.74 431.23]
 [462.79 460.01]
 [466.28 461.14]
 ...
 [473.55 473.26]
 [440.26 438.  ]
 [459.51 463.28]]
